### ISSUE TITLE
 [Frontend] Design User Registration and Login Pages

### ISSUE THREAD

**Issue by MohamedElsadany56** [MohamedElsadany56/JobFinder#3]
**Description:**

**Feature:** 
Create intuitive forms for user registration and login.
**UI Elements:**
 Input fields, validation messages, and responsive layout.
**Acceptance Criteria:**

- Pages match design specifications.
- Forms validate inputs before submission.
- Integrated with backend endpoints for registration and login.

**Comment by mohamedmasodabozed** [comment]
Created the Registration and Login Pages FrontEnd
