### ISSUE TITLE
[Frontend] Create Task Posting Form

### ISSUE THREAD

**Issue by MohamedElsadany56** [MohamedElsadany56/JobFinder#5]
**Description:**

**Feature:**
Develop a form for task posters to submit new tasks.
**UI Elements:** 
Fields for title, description, location, and date.
**Acceptance Criteria:**

- Form validates input before submission.
- Integrated with the task posting API.

**Comment by mohamedmasodabozed** [comment]
Created the Task Posting Form FrontEnd
