### ISSUE TITLE
[Frontend] Build Task Filtering Interface

### ISSUE THREAD

**Issue by MohamedElsadany56** [MohamedElsadany56/JobFinder#7]
**Description:**

**Feature:** 
Design a dynamic filtering UI for task seekers.
**UI Elements:**
Dropdowns, search bars, and filters.
**Acceptance Criteria:**

- Filters are functional and integrated with the backend.
- Interface is responsive and user-friendly.

**Comment by mohamedmasodabozed** [comment]
Done
